@startuml
'https://plantuml.com/component-diagram

actor user
node "microservice-kubernetes-demo" {
    rectangle "demo-catalog-customer" as demoCatalogCustomer #line.dashed {
        component "catalog-service" as catalogService
        component "customer-service" as customerService
    }

    rectangle "demo-order" as demoOrder #line.dashed {
        component "order-service" as orderService
    }

    component "apache-http" as apacheHttp
}

user -up(0- apacheHttp: HTTP

catalogService -0)- apacheHttp: REST
customerService -0)- apacheHttp: REST
orderService -0)- apacheHttp: REST

catalogService -right0)- orderService: REST
customerService -down0)- orderService: REST
@enduml
